CREATE TABLE IF NOT EXISTS MODES (
    MODE_NAME TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS SEASONS (
    SEASON_ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_NAME TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID TEXT NOT NULL,
    SEASON_ID INTEGER NOT NULL,
    MODE_NAME TEXT NOT NULL,
    POINTS INTEGER NOT NULL DEFAULT 0,
    PREDICTIONS INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_NAME) REFERENCES MODES(MODE_NAME) ON DELETE CASCADE,
    PRIMARY KEY (SEASON_ID, USER_ID, MODE_NAME)
);

CREATE TABLE IF NOT EXISTS GAMES (
    GAME_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SEASON_ID INTEGER NOT NULL,
    MODE_NAME TEXT NOT NULL,
    GAME_STATUS INTEGER NOT NULL DEFAULT 0,
    GAME_FIELD INTEGER NOT NULL,
    GAME_DAY TEXT NOT NULL,
    OPPONENT_ID TEXT NOT NULL,
    PREDICTIONS INTEGER NOT NULL DEFAULT 0,
    WINNERS INTEGER NOT NULL DEFAULT 0,
    GOALS_SCORED INTEGER NOT NULL DEFAULT 0,
    GOALS_SUFFERED INTEGER NOT NULL DEFAULT 0,

    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_NAME) REFERENCES MODES(MODE_NAME) ON DELETE CASCADE,
    FOREIGN KEY (OPPONENT_ID) REFERENCES TEAMS(MODE_NAME) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS PREDICTIONS (
    GAME_ID INTEGER NOT NULL,
    USER_ID TEXT NOT NULL,
    GOALS_HOME INTEGER NOT NULL,
    GOALS_AWAY INTEGER NOT NULL,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (GAME_ID, USER_ID)
);

INSERT INTO MODES VALUES ("Futebol"), ("Futsal"), ("Seleção");
INSERT INTO SEASONS VALUES (2425);
