CREATE TABLE IF NOT EXISTS MODES (
    MODE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODE_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SEASONS (
    SEASON_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SEASON_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEAM_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID TEXT NOT NULL,
    SEASON_ID INTEGER NOT NULL,
    MODE_ID INTEGER NOT NULL,
    POINTS INTEGER NOT NULL DEFAULT 0,
    PREDICTIONS INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_ID) REFERENCES MODES(MODE_ID) ON DELETE CASCADE,
    PRIMARY KEY (SEASON_ID, USER_ID, MODE_ID)
);

CREATE TABLE IF NOT EXISTS GAMES (
    GAME_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SEASON_ID INTEGER NOT NULL,
    MODE_ID INTEGER NOT NULL,
    GAME_STATUS INTEGER NOT NULL DEFAULT 0,
    GAME_FIELD INTEGER NOT NULL,
    GAME_DAY TEXT NOT NULL,
    OPPONENT_ID INTEGER NOT NULL,
    PREDICTIONS INTEGER NOT NULL DEFAULT 0,
    WINNERS INTEGER NOT NULL DEFAULT 0,
    GOALS_SCORED INTEGER NOT NULL DEFAULT 0,
    GOALS_SUFFERED INTEGER NOT NULL DEFAULT 0,

    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_ID) REFERENCES MODES(MODE_ID) ON DELETE CASCADE,
    FOREIGN KEY (OPPONENT_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS PREDICTIONS (
    GAME_ID INTEGER NOT NULL,
    USER_ID TEXT NOT NULL,
    GOALS_HOME INTEGER NOT NULL,
    GOALS_AWAY INTEGER NOT NULL,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (GAME_ID, USER_ID)
);
