name: Bot Gverreiro Tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      THREADS: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'oracle'
          
      - name: Build and run tests
        working-directory: BotDiscord
        run: mvn test